### PR TITLE
Allow custom options to be passed to request()

### PR DESCRIPTION
**Pull request by kamaln7**
This allows the user to pass custom options to the request library such as HTTP Headers.

The expand() function can now be used in two ways:

``` javascript
expand(shortURL, callback);
// or
expand(shortURL, options, callback);
```

I also added a test which overrides the 'url' option.

### CODE REVIEW

**Comment by ttback** [comment]
Thank for your contribution, i will take a quick look at it tonight. :)

**Comment by kamaln7** [comment]
Thanks! Could you please bump the version number in `package.json` and run `npm publish` so that the changes are published?

**Comment by ttback** [comment]
sure, published now. :+1:

**Comment by kamaln7** [comment]
Weird, it doesn't look like it was updated. Have you run `git pull` before publishing it? If not, you'll need to pull the changes, bump the version number again, and then run `npm publish`.

**Comment by ttback** [comment]
double-checked, and published again. It should be there now.

**Comment by kamaln7** [comment]
Works now. Thank you! :+1:

**Comment by ttback** [comment]
@kamaln7 no problem, thank you for contributing. :D

**Comment by ttback** [comment]
@kamaln7 Feel free to let me know if you see any feature request for this utility too. So far I think there's nothing more to add for a very simple utility like this.

**Pull request merged**
